releaseProvider: gitlab
tasksProvider: gitlab
template: stylish_markdown
tasksPipes: [ 'gitlab_resolver', 'natural_language' ]
tasksPipesCfg:
  inclusions_exclusions:
    labels:
      excluded: [ 'scope::internal' ]