image: golang:1.17.3

stages:
  - prepare-release
  - release

variables:
  REPO_NAME: gitlab.com/aoterocom/changelog-guardian

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

prepare-release:
  stage: prepare-release
  script:
    - git config user.name "$GIT_USERNAME"
    - git config user.email "$GIT_EMAIL"
    - go get $(go list ./... | grep -v /vendor/)
    - go run main.go release --silent > VERSION
    - git branch release/$(cat VERSION)
    - git checkout release/$(cat VERSION)
    - git add VERSION CHANGELOG.md
    - git commit -m "[AUTOMATED] Release $(cat VERSION)"
    - RELEASE_NOTES=$(go run main.go release-notes --echo)
    - git push -o ci-skip https://gitlab-ci-token:${GITLAB_PUSH_TOKEN}@gitlab.com/aoterocom/changelog-guardian.git
    - |
      curl --location --request POST "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests" \
      --header "PRIVATE-TOKEN:$GITLAB_PUSH_TOKEN" \
      --form 'id="'"$CI_PROJECT_ID"'"' \
      --form "title=\"Release $(cat VERSION)\"" \
      --form "source_branch="release/$(cat VERSION)"" \
      --form 'target_branch="main"' \
      --form 'description="'"$RELEASE_NOTES"'"'
  rules:
    - if: '$TRIGGER == "RELEASE"'

release:
  stage: release
  script:
    - git config user.name "$GIT_USERNAME"
    - git config user.email "$GIT_EMAIL"
    - git tag v$(cat VERSION)
    - git push origin v$(cat VERSION) -o ci-skip https://${GITLAB_PUSH_TOKEN}@gitlab.com/aoterocom/changelog-guardian
    - go get $(go list ./... | grep -v /vendor/)
    - go install github.com/goreleaser/goreleaser@latest
    - go run main.go release-notes
    - git branch release/prepare-iteration-$(cat VERSION)
    - git checkout release/prepare-iteration-$(cat VERSION)
    - go run main.go calculate-release --pre SNAPSHOT > VERSION
    - git add VERSION
    - git commit -m "[AUTOMATED] Prepare for next iteration $(cat VERSION)"
    - git push -o ci-skip https://gitlab-ci-token:${GITLAB_PUSH_TOKEN}@gitlab.com/aoterocom/changelog-guardian.git
    - |
      curl --location --request POST "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests" \
      --header "PRIVATE-TOKEN:$GITLAB_PUSH_TOKEN" \
      --form 'id="'"$CI_PROJECT_ID"'"' \
      --form "title=\"Release $(cat VERSION)\"" \
      --form "source_branch="release/prepare-iteration-$(cat VERSION)"" \
      --form 'target_branch="develop"' \
      --form 'description="This PR will prepare develop for the next release iteration $(cat VERSION)"'
  rules:
    - if: '$TRIGGER == "PREPARE"'