image: golang:1.17.3

stages:
  - testRelease

variables:
  REPO_NAME: gitlab.com/aoterocom/changelog-guardian

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

format:
  stage: testRelease
  script:
    echo "$GIT_PGP_KEY" | gpg --import
    git config user.name $GIT_USERNAME
    git config user.email $GIT_EMAIL
    git config commit.gpgsign true

    go run main.go release --silent > VERSION
    git checkout release/$(cat VERSION)
    git commit -m “Release $(cat VERSION)”
    cat VERSION
    #git tag v$(cat VERSION)
    git push
