image: golang:1.17.3

stages:
  - release

variables:
  REPO_NAME: gitlab.com/aoterocom/changelog-guardian

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

release:
  stage: release
  script:
    - git config user.name "$GIT_USERNAME"
    - git config user.email "$GIT_EMAIL"
    - git branch -a
    - go get $(go list ./... | grep -v /vendor/)
    - go run main.go release --silent > VERSION
    - git branch release/$(cat VERSION)
    - git checkout release/$(cat VERSION)
    - git add VERSION CHANGELOG.md
    - git commit -m "[AUTOMATED] Release $(cat VERSION)"
    - git push -o ci-skip https://gitlab-ci-token:${GITLAB_PUSH_TOKEN}@gitlab.com/aoterocom/changelog-guardian.git
      -o merge_request.create -o merge_request.target=main -o merge_request.title="Release $(cat VERSION)"
      -o merge_request.description="$(go run main.go release-notes --echo)"
  only:
    - merge_requests
    - develop